outliers_range = 1
cost = 0.001

[search_space]
resample_interval = [1, 3, 5, 15, 30, 60]
decay_factor = [1, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
mode = [1, 2, 3]

[search_space.ma]
lead = [5, 100, 2]
lag = [10, 200, 3]

[search_space.rsi]
detrend = [2, 100, 2]
rsi_period = [1, 100, 2]

[search_space.wr]
timeperiod = [2, 500, 2]

[search_space.cci]
timeperiod = [2, 500, 2]

[benchmark]
sharpe_ratio = 1.5
max_drawdown = -10
daily_trades = 5
win_rate = 50
sortino_ratio = 2.26
linearity = 80
calmar_ratio = 10

[rs_scoring_weights]
sharpe_ratio = 20
max_drawdown = 20
daily_trades = 0
win_rate = 0
sortino_ratio = 20
linearity = 10
calmar_ratio = 10

[ls_scoring_weights]
sharpe_ratio = 0
max_drawdown = 10
daily_trades = 40
win_rate = 30
sortino = 15
linearity = 5
calmar = 0
